### ISSUE TITLE
Theme: TokyoNight

### ISSUE THREAD

**Issue by Zeioth** [weirongxu/coc-markdown-preview-enhanced#6]
Hi, I wrote a TokyoNight theme for coc-markdown-preview-enhanced that mirrors exactly the appearance of vim's TokyoNight's theme. You can see a photo and the code here. I'd really appreciate if anyone reading this add wathever you consider is lacking. Enjoy.

![screenshot_2021-12-26_20-21-36_990650445](https://user-images.githubusercontent.com/3357792/147418004-7c8d66be-8c72-4f67-bbfb-8ca6f9e7db92.png)

```css
/* Please visit the URL below for more information: */
/*   https://shd101wyy.github.io/markdown-preview-enhanced/#/customize-css */

// TODO: Remove title bar.

.markdown-preview {
  // modify your style here
  // Current theme: tokyo night.

  // Disable antialiasing
  font-smooth: never;
  -webkit-font-smoothing : none;

  // Font
  font-family: "RobotoMono Nerd Font Mono";
  font-size: 0.75em;
  font-weight: 405;
  h1,h2,h3,h4,h5,h6{font-size: 1.00em}

  // Set colors
  background-color: #1a1b26;
  color: #a9b1d6;
  h1{color: #f7768e}
  h2{color: #ff9e64}
  h3{color: #e0af68}
  h4{color: #9ece6a}
  h5{color: #7aa2f7}
  h6{color: #ad8ee6}
  ::-moz-list-bullet{color: #f7768e}


  // Code font and bg
  pre,code{
    font-family: "RobotoMono Nerd Font Mono";
    font-size: 0.75em;
    background-color: #191b1c;
    color: #b1ada8;
  }

  // html links
  a:link{
  color: #7aa2f7;
  font-weight: 400;
  }
}

// Sidebar color
.md-sidebar-toc {background-color: #1a1b26}

// Restore opacity + hide useless buttons
#md-toolbar {
  .back-to-top-btn{display: none}
  .refresh-btn{display: none}
  .sidebar-toc-btn{
    opacity: 1;
    margin-top: 0px;
  }
}
```
